Use navigate
vtex-apps/add-to-cart-button pull request #50
Opened 2020-09-22 14:31 UTC by vitorflg

#### What problem is this solving?

Use navigate when redirecting to checkout cart to permit adding the loading bar on top of the document. Also remove the "Item added to cart" toaster in this use case.

#### How to test it?

In the workspace try to add to cart and verify if everything is ok( with the redirect) and if the document has a loading bar in the process.

https://vitorflg--storecomponents.myvtex.com/

[Workspace](Link goes here!)

#### Screenshots or example usage:

X

#### Describe alternatives you've considered, if any.

X

#### Related to / Depends on

https://github.com/vtex-apps/render-runtime/pull/567

2020-09-22 15:13 UTC, kaisermann requested changes

2020-09-22 15:13 UTC, kaisermann commented on CHANGELOG.md
> +- Use navigate when redirecting to checkout
```suggestion
- Use `navigate()` when redirecting to the checkout
```

2020-09-22 15:13 UTC, kaisermann commented on react/AddToCartButton.tsx
> +    if (isFakeLoading && !isOneClickBuy) {
Fix the linter error here 😁

2020-09-22 15:13 UTC, kaisermann commented on react/AddToCartButton.tsx
>        }, FAKE_LOADING_DURATION))
```suggestion
      timers.current.toast = window.setTimeout(() => {
        toastMessage({ success: true })
      }, FAKE_LOADING_DURATION)
```

2020-09-23 15:44 UTC, victorhmp approved these changes

2020-09-23 16:58 UTC, klzns requested changes

2020-09-23 16:58 UTC, klzns commented on react/AddToCartButton.tsx
> +          to: `${customOneClickBuyLink ?? checkoutURL}`,
Make sure navigate handles rootPath

2020-09-24 06:26 UTC, vitorflg commented on react/AddToCartButton.tsx
> +          to: `${customOneClickBuyLink ?? checkoutURL}`,
It handles!

2020-09-24 14:36 UTC, iaronaraujo approved these changes

2020-09-28 15:11 UTC, klzns approved these changes

2020-09-29 13:25 UTC, kaisermann approved these changes

2020-10-13 20:27 UTC, merged