Fix/SKU selector consistency
vtex-apps/add-to-cart-button pull request #87
Opened 2021-07-07 15:42 UTC by igorbrasileiro

#### What problem is this solving?
Prevent the user clicks on this button while the new selectedItem is being processed.

Disable the add to cart button, while loadingItem is true.

#### How to test it?
[Workspace](https://brasileiro--melisseiras.myvtex.com/melissa-sun-rodeo-vermelho-33530/p?skuId=135439)

1. Chose another SKU, via SKU selector
2. Click on add to cart button
3. Check if the correct SKU is added to the minicart.

#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on
https://github.com/vtex-apps/product-context/pull/61
https://github.com/vtex-apps/store-components/pull/960

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/duL28c2tptZ0zAopCf/giphy.gif)

2021-07-27 14:23 UTC, victorhmp requested changes

2021-07-30 20:03 UTC, icazevedo approved these changes

2021-08-02 18:48 UTC, victorhmp approved these changes

2021-08-02 18:49 UTC, victorhmp requested changes
Just noticed that the tests are failing

2021-08-02 20:00 UTC, victorhmp approved these changes

2021-08-03 13:09 UTC, igorbrasileiro commented
The Danger is warning because the last PR was not released and when a merged the changelog into the same added section, but the diff doesn't belong to my PR.

2021-08-03 14:05 UTC, victorhmp approved these changes

2021-08-03 14:11 UTC, merged